# Generated by Django 6.0.1 on 2026-01-29 14:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='quest',
            index=models.Index(fields=['status', 'end_time'], name='quests_ques_status_d69a2c_idx'),
        ),
    ]
