# Generated by Django 6.0.1 on 2026-01-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_quest_quests_ques_status_d69a2c_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='rarity',
            field=models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('diamond', 'Diamond')], default='silver', max_length=20),
        ),
        migrations.AddField(
            model_name='quest',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('insane', 'Insane')], default='medium', max_length=20),
        ),
    ]
